---
- name: Instalează și configurează aplicația de laborator 
  hosts: localhost
  connection: local
  become: yes

  vars:
    nume_student: "catalin_moisei"
    locatie_cod: "/var/www/laborator_{{ nume_student }}"
    nume_server: "laborator.local"
    git_repo_url: "https://github.com/catcyb/laborator_cybersecurity.git"

  tasks:
    - name: "Update package cache "
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      ignore_errors: yes 

    - name: "instalează apache și git"
      ansible.builtin.package:
        name: "apache2"
        state: present

    - name: "pornește serviciul apache și setează-l să pornească la boot"
      ansible.builtin.service:
        name: "apache2"
        state: started
        enabled: yes

    - name: "ia codul de pe git"
      ansible.builtin.git:
        repo: "{{ git_repo_url }}"
        dest: "{{ locatie_cod }}"
        clone: yes
        #update: yes # dacă este rulat de mai multe ori, nu face decât să ia versiunea nouă
        #force: yes # forțează actualizarea dacă există modificări locale
        version: "main"

    - name: "permisiuni pentru cod"
      ansible.builtin.file:
        path: "{{ locatie_cod }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        recurse: yes

    - name: "vezi ca exista directorul pentru virtual host"
      ansible.builtin.file:
        path: "/etc/apache2/sites-available/"
        state: directory
        mode: '0755'

    - name: "fă virtual host pentru apache"
      ansible.builtin.copy:
        dest: "/etc/apache2/sites-available/laborator_{{ nume_student }}.conf"
        content: |
          <VirtualHost *:80>
              ServerAdmin webmaster@{{ nume_server }}
              ServerName {{ nume_server }}
              DocumentRoot {{ locatie_cod }}
              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
              <Directory {{ locatie_cod }}>
                  AllowOverride All
                  Require all granted
              </Directory>
          </VirtualHost>
      notify: Restart Apache

    - name: "activeaza noul site"
      ansible.builtin.command:
        cmd: "a2ensite laborator_{{ nume_student }}.conf"
      when: ansible_os_family == "Debian"
      notify: Restart Apache
      changed_when: true 

    - name: "dezactiveaza site-ul default"
      ansible.builtin.file:
      state: absent
      path: /etc/apache2/sites-enabled/000-default.conf
      notify: Restart Apache
      

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: "apache2"
        state: restarted
