---
- name: Install and configure Apache web server
  hosts: localhost
  connection: local
  become: yes

  vars:
    apache_package_name: "apache2"
    apache_service_name: "apache2"

  tasks:
    - name: "Update package cache (for Debian/Ubuntu)"
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      ignore_errors: yes # In case apt is not available

    - name: "Install Apache package"
      ansible.builtin.package:
        name: "{{ apache_package_name }}"
        state: present

    - name: "Start and enable Apache service"
      ansible.builtin.service:
        name: "{{ apache_service_name }}"
        state: started
        enabled: yes